name: Checks

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clippy:
    name: Clippy
    runs-on: ubicloud-standard-2
    steps:
      - uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        # with:
        #   extra_nix_config: |
        #     experimental-features = nix-command flakes
        #     access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Run Clippy
        run: nix develop --command cargo clippy --all-targets --all-features

  nix-flake-check:
    name: Nix Flake Checks
    # Using this "needs" keyword decreases the computational resources if clippy-check fails.
    # But it also increases CI runtime if clippy-check succeeds.
    # needs: clippy-check
    runs-on:
      - ubicloud-standard-4
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Check
        run: nix flake check . --print-build-logs
