name: Quality Assurance & Package Deployments

on:
  pull_request: null
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clippy-check:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        # with:
        #   extra_nix_config: |
        #     experimental-features = nix-command flakes
        #     access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Run Clippy
        run: nix develop --command cargo clippy --all-targets --all-features

  nix-flake-check:
    name: Run Nix checks
    # Using this "needs" keyword decreases the computational resources if clippy-check fails.
    # But it also increases CI runtime if clippy-check succeeds.
    # needs: clippy-check
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Check
        run: nix flake check . --print-build-logs

  nightly-builds:
    name: Nightly builds
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Nightly builds
        run: |
          mkdir artifacts
          for f in $(nix build --print-build-logs --print-out-paths .#packages.x86_64-linux.daisyway-deb .#packages.x86_64-linux.daisyway-tar); do cp "$f" "artifacts/${f#*-}"; done
          echo >&2
          echo >&2 "Generated artifacts:"
          find ./artifacts >&2
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: nightly-build
          path: artifacts/*
